// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NtBot.Infrastructure.Persistence;

#nullable disable

namespace NtBot.Infrastructure.Migrations;

[DbContext(typeof(NtBotDbContext))]
[Migration("20260922150000_AddWhiteLabelPortfolio")]
partial class AddWhiteLabelPortfolio
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Target model is maintained via NtBotDbContext + WhiteLabelPortfolioSchemaBootstrap.
#pragma warning disable CS0612
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore CS0612
    }
}
