// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NtBot.Infrastructure.Persistence;

#nullable disable

namespace NtBot.Infrastructure.Migrations
{
    [DbContext(typeof(NtBotDbContext))]
    [Migration("20260805183000_AddBoletagem")]
    partial class AddBoletagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is maintained via NtBotDbContext + BoletagemSchemaBootstrap.
            // Full snapshot regeneration: dotnet ef migrations add / remove when Api is stopped.
        }
    }
}
