<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\ProfitService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Core" Version="2.3.9" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.Formats.Asn1" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="dlls\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketData.ProfitDLL\MarketData.ProfitDLL.csproj" />
    <ProjectReference Include="..\Marketdata.Database\Marketdata.Database.csproj" />
    <ProjectReference Include="..\Orbital.Core\Orbital.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Worker\Simulator\mock_marketdata.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Signarl.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
	<!-- MarketData.API.csproj -->
  <ItemGroup>
    <None Update="dlls\HadesSSLServerAddr3.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\holidays.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\InfoSSLServerAddr3.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\libcrypto-1_1-x64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\libeay32.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\libssl-1_1-x64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\newagents.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\ProfitChart.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\ProfitDLL.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\ReplayServerAddr3.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\ServerAddr6.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\ssleay32.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dlls\timezone2.dat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ProfitDLL.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
